"""empty message

Revision ID: 540d5c8ea98d
Revises: 
Create Date: 2017-06-13 18:26:43.174127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540d5c8ea98d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bind_cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster', sa.String(length=64), nullable=True),
    sa.Column('bind_ip', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dns_host',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('data', sa.String(length=64), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('cluster', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster'),
    sa.UniqueConstraint('data'),
    sa.UniqueConstraint('host'),
    sa.UniqueConstraint('port'),
    sa.UniqueConstraint('priority'),
    sa.UniqueConstraint('status'),
    sa.UniqueConstraint('ttl'),
    sa.UniqueConstraint('type'),
    sa.UniqueConstraint('weight'),
    sa.UniqueConstraint('zone')
    )
    op.create_table('dns_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('master_domain', sa.String(length=64), nullable=True),
    sa.Column('mail_domain', sa.String(length=64), nullable=True),
    sa.Column('soa_serial', sa.Integer(), nullable=True),
    sa.Column('soa_refresh', sa.Integer(), nullable=True),
    sa.Column('soa_retry', sa.Integer(), nullable=True),
    sa.Column('soa_expire', sa.Integer(), nullable=True),
    sa.Column('soa_minimum', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail_domain'),
    sa.UniqueConstraint('master_domain'),
    sa.UniqueConstraint('soa_expire'),
    sa.UniqueConstraint('soa_minimum'),
    sa.UniqueConstraint('soa_refresh'),
    sa.UniqueConstraint('soa_retry'),
    sa.UniqueConstraint('soa_serial')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('dns_zone')
    op.drop_table('dns_host')
    op.drop_table('bind_cluster')
    # ### end Alembic commands ###
